$schema: https://json-schema.org/draft/2020-12/schema
title: ADA LC-MS Product Profile
description: >-
  Technique-specific profile for Liquid Chromatography Mass Spectrometry (LC-MS) products.
  Extends the base ADA product profile with constraints on valid LC-MS component
  types.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a LC-MS product type identifier.
        contains:
          enum:
            - "Liquid Chromatography - Mass Spectrometry (LCMS) Collection"
            - "Liquid chromatography-mass spectrometry"
      "schema:distribution":
        items:
          oneOf:
            - required:
                - componentType
              properties:
                componentType:
                  anyOf:
                    - properties:
                        "@type":
                          enum:
                            - "ada:LCMSCollection"
                            - "ada:LCMSMSCollection"
                    - $ref: ../adaProduct/schema.yaml#/$defs/universalComponentType
            - required:
                - "schema:hasPart"
              properties:
                "schema:hasPart":
                  items:
                    properties:
                      componentType:
                        anyOf:
                          - properties:
                              "@type":
                                enum:
                                  - "ada:LCMSCollection"
                                  - "ada:LCMSMSCollection"
                          - $ref: ../adaProduct/schema.yaml#/$defs/universalComponentType
