---
$schema: https://json-schema.org/draft/2020-12/schema
type: object
title: DDE Image profile
description: DDE profile for image resources (image, photograph, explanatoryFigure,
  map). Extends DDEDiscovery with resource type constraint and ddeImagery
  conditional properties.
allOf:
- $ref: ../DDEDiscovery/schema.yaml
- $ref: ../../../DDEproperties/ddeImagery/schema.yaml
- properties:
    'schema:additionalType':
      contains:
        type: object
        properties:
          '@type':
            const: schema:DefinedTerm
          'schema:inDefinedTermSet':
            const: 'dde:codelist/ResourceTypeCode'
          'schema:termCode':
            type: string
            enum:
            - image
            - map
            - photograph
            - explanatoryFigure
        required:
        - '@type'
        - 'schema:inDefinedTermSet'
        - 'schema:termCode'
      minContains: 1
