---
$schema: https://json-schema.org/draft/2020-12/schema
title: definitions for simple quality measure property
type: object
properties:
  '@type':
    anyOf:
    - type: string
      const: dqv:QualityMeasurement
    - type: array
      items:
        type: string
      contains:
        const: dqv:QualityMeasurement
  'dqv:isMeasurementOf':
    description: specify the quality measure that is reported, by name, with an ID ref, or as a Defined
      Term
    anyOf:
    - type: string
    - type: object
      properties:
        '@id':
          type: string
          description: a resolvable reference to a representation of a quality measure
    - $ref: '#/$defs/DefinedTerm'
  'dqv:value':
    description: the reported result of the quality measure, either as a string or a defined term from
      a vocabulary
    anyOf:
    - type: string
    - $ref: '#/$defs/DefinedTerm'
required:
- 'dqv:isMeasurementOf'
- 'dqv:value'
$defs:
  DefinedTerm:
    $ref: ../../schemaorgProperties/definedTerm/schema.yaml