$schema: https://json-schema.org/draft/2020-12/schema
description: schema to document file-based access to a resoruce via URL, based on schema.org/DataDownload
type: object
properties:
  '@id': 
    type: string
  '@type':
    type: array
    description: implement as array because extensions might need to add additional types
    items:
      type: string
    contains:
      const: schema:DataDownload
    minItems: 1
  'schema:name':
    type: string
  'schema:contentUrl':
    type: string
    format: uri
  'schema:encodingFormat':
    type: array
    description: MIME type with extension; should indicate the serialization scheme in sufficient detail
        that machine can know how to parse.
    items:
      type: string
  'spdx:checksum':
    type: object
    description: A string value calculated from the content of the resource representation, used to test
      if content has been modified. The checksum is a property of a particular distribution/DataDownload.
    properties:
      '@type':
        anyOf:
          - type: string
            const: 'spdx:Checksum'
          - type: array
            items:
              type: string
            contains:
              const: 'spdx:Checksum'
      'spdx:algorithm':
        type: string
      'spdx:checksumValue':
        type: string
    required:
      - '@type'
  'schema:provider':
    type: array
    description: Party who maintains this particular distribution option for the dataset. Use this property
      if there are multiple distributions from different providers
    items:
      anyOf:
      - type: object
        properties:
          '@id':
            type: string
            description: a identifier for an agent defined in this metadata, or externally; must be dereferenceable
      - $ref: ../person/schema.yaml
      - $ref: ../organization/schema.yaml
required:
- 'schema:contentUrl'
- '@type'