---
$schema: https://json-schema.org/draft/2020-12/schema
type: object
title: DDE Document profile
description: DDE profile for document resources (document, article, thesis, book,
  poster, webPage). Extends DDEDiscovery with resource type constraint.
allOf:
- $ref: ../DDEDiscovery/schema.yaml
- properties:
    'schema:additionalType':
      contains:
        type: object
        properties:
          '@type':
            const: schema:DefinedTerm
          'schema:inDefinedTermSet':
            const: 'dde:codelist/ResourceTypeCode'
          'schema:termCode':
            type: string
            enum:
            - document
            - article
            - thesis
            - book
            - poster
            - webPage
        required:
        - '@type'
        - 'schema:inDefinedTermSet'
        - 'schema:termCode'
      minContains: 1
