$schema: https://json-schema.org/draft/2020-12/schema
title: ADA ICP-OES Product Profile
description: >-
  Technique-specific profile for Inductively Coupled Plasma Optical Emission Spectrometry (ICP-OES) products.
  Extends the base ADA product profile with constraints on valid ICP-OES component
  types and detailICPOES requirements.
allOf:
  - $ref: ../adaProduct/schema.yaml
  - type: object
    properties:
      "schema:additionalType":
        description: >-
          Must include a ICP-OES product type identifier.
        contains:
          enum:
            - "Inductively Coupled Plasma - Optical Emission Spectroscopy (ICPOES) Raw"
            - "Inductively Coupled Plasma - Optical Emission Spectroscopy (ICPOES) Intermediate"
            - "Inductively Coupled Plasma - Optical Emission Spectroscopy (ICPOES) Processed"
            - "Inductively coupled plasma - optical emission spectrometry"
      "schema:distribution":
        items:
          oneOf:
            - required:
                - componentType
              properties:
                componentType:
                  anyOf:
                    - properties:
                        "@type":
                          enum:
                            - "ada:ICPOESIntermediateTabular"
                            - "ada:ICPOESProcessedTabular"
                            - "ada:ICPOESRawTabular"
                    - $ref: ../adaProduct/schema.yaml#/$defs/universalComponentType
            - required:
                - "schema:hasPart"
              properties:
                "schema:hasPart":
                  items:
                    properties:
                      componentType:
                        anyOf:
                          - properties:
                              "@type":
                                enum:
                                  - "ada:ICPOESIntermediateTabular"
                                  - "ada:ICPOESProcessedTabular"
                                  - "ada:ICPOESRawTabular"
                          - $ref: ../adaProduct/schema.yaml#/$defs/universalComponentType
