---
$schema: https://json-schema.org/draft/2020-12/schema
type: object
title: CDIF Data Description metadata profile
description: >-
  CDIF Data Description profile. Composes cdifCore with discovery properties
  and data description extensions for detailed variable and structure
  documentation.
allOf:
- $ref: ../../../cdifProperties/cdifCore/schema.yaml
- $ref: ../../../cdifProperties/cdifDataDescription/schema.yaml
- type: object
  properties:
    '@context':
      type: object
      description: Additional JSON-LD namespace prefixes for discovery and data description.
      properties:
        geosparql:
          const: "http://www.opengis.net/ont/geosparql#"
        dqv:
          const: "http://www.w3.org/ns/dqv#"
        cdi:
          const: "http://ddialliance.org/Specification/DDI-CDI/1.0/RDF/"
    'schema:measurementTechnique':
      description: The technique, technology, or methodology used for measurement or
        determination of the dataset values.
      anyOf:
      - type: string
      - $ref: '#/$defs/DefinedTerm'
      - type: array
        items:
          anyOf:
          - type: string
          - $ref: '#/$defs/DefinedTerm'
    'schema:spatialCoverage':
      description: Geographic extent of resource content.
      type: array
      items:
        $ref: '#/$defs/SpatialExtent'
    'schema:temporalCoverage':
      description: Temporal extent of resource content.
      type: array
      items:
        $ref: '#/$defs/TemporalExtent'
    'dqv:hasQualityMeasurement':
      description: Quality measurements reported to assess the resource.
      type: array
      items:
        $ref: '#/$defs/QualityMeasure'
    'schema:subjectOf':
      properties:
        'dcterms:conformsTo':
          contains:
            type: object
            properties:
              '@id':
                const: 'https://w3id.org/cdif/dataDescription/1.0/'
$defs:
  DefinedTerm:
    $ref: ../../../schemaorgProperties/definedTerm/schema.yaml
  SpatialExtent:
    $ref: ../../../schemaorgProperties/spatialExtent/schema.yaml
  TemporalExtent:
    $ref: ../../../schemaorgProperties/temporalExtent/schema.yaml
  QualityMeasure:
    $ref: ../../../qualityProperties/qualityMeasure/schema.yaml
